# Generated by Django 4.2.7 on 2023-12-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation_sale', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('reservation_sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation_sale.reservation_sale')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.services')),
            ],
        ),
    ]
