# Generated by Django 4.2.7 on 2023-12-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('cabin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabin.cabin')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Customer.customer')),
            ],
        ),
    ]
