# Generated by Django 4.2.7 on 2023-12-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_sale',
            name='cabin',
        ),
        migrations.RemoveField(
            model_name='reservation_sale',
            name='description',
        ),
    ]
