# Generated by Django 4.2.7 on 2023-12-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('cabin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cant', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('idCabin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cabin.cabin')),
                ('idFacilities', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facilities')),
            ],
        ),
    ]
