# Generated by Django 4.2.7 on 2023-12-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabin_facility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabin_facility',
            old_name='Cant',
            new_name='amount',
        ),
    ]
