# Generated by Django 4.2.7 on 2023-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
