# Generated by Django 4.2.7 on 2023-12-05 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_date', models.DateField()),
                ('score', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('reservation_sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qualification.qualification')),
            ],
        ),
    ]
