# Generated by Django 4.2.7 on 2023-12-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_sale', '0001_initial'),
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='reservation_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation_sale.reservation_sale'),
        ),
    ]
